### ISSUE TITLE
Dell PowerVault ME4 CheckMK 2.0: configurable parameters

### ISSUE THREAD

**Issue by mbunkus** [Yogibaer75/Check_MK-Things#5]
At the moment parameters such as the disk temperature aren't configurable. The check itself is prepared for it, it seems (it includes default parameters & rule names), but there are no rule definitions.

**Comment by Yogibaer75** [comment]
Temperature on disk checks is now configurable. It uses the default temperature rules from CMK. For the sensor checks this would not be so easy as there it is needed to build a own rule setup as there are different sensor types in a single check.
Fixed with https://github.com/Yogibaer75/Check_MK-Things/commit/3bdcd2449cbe4e6c178c281f9b705f7e36cad2a9

**Comment by mbunkus** [comment]
Thank you so much. Disk temperature is indeed what I need at the moment as our disks are just around 40 C, some slightly over that.
