### ISSUE TITLE
Windows DeDup Plugin - Error after Upgrade to 2.2.0p23

### ISSUE THREAD

**Issue by FloMeh** [Yogibaer75/Check_MK-Things#52]
Hello,
we updated from version 2.1 to version 2.2.0p23.
Since then, the plugin crashes during automatic execution.

![image](https://github.com/Yogibaer75/Check_MK-Things/assets/70646156/3c7a97c7-f70b-4e26-ac04-a0ebbc8fe751)

In the Service Discovery, the system still shows OK and the correct values, but as soon as we take over the service and it tries to update, the crash report appears.
Is there a solution for this? Currently, I'm not sure where to start or what to do.

**Comment by Yogibaer75** [comment]
Ok the problem is that this plugin is original for 2.0 CMK and that it is working with 2.1 is more random luck :)
As i have no system available that is using Windows dedup functionality at the moment, i need the actual agent output of one system to test the plugin with 2.2.
It is only the dedup section i need not the complete agent output.

**Comment by FloMeh** [comment]
The agent output for the area is as follows.
![image](https://github.com/Yogibaer75/Check_MK-Things/assets/70646156/26faf1b1-25f6-4a48-8137-535e8dacb144)

![image](https://github.com/Yogibaer75/Check_MK-Things/assets/70646156/b49c4f18-783d-42d5-94a6-5cdf09ca75f7)

As previously described, the strange thing is that during discovery everything is still displayed correctly and only then after adding the service to the host and after updating does the crash occur.

**Comment by Yogibaer75** [comment]
With commit 9288fbc the Windows deduplication plugin is completely migrated to CMK 2.3.
I hope that there are no problems anymore.
